-define(PRINT(Var), io:format("DEBUG: ~p:~p - ~p~n~n ~p~n~n", [?MODULE, ?LINE, ??Var, Var])).
-define(SAMPLERATE, 16000).
-define(CHANNELS, 2).
-define(NUM_SOUND_PORTS, 3).
-record(on, {ticks, controller, note, amplitude}).
-record(off, {ticks, controller, note, amplitude}).
-record(note, {start, length, controller, note, amplitude}).
